name: ci
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'composer.lock'
    branches:
      - '*'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 30
          persist-credentials: false

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          bootstrap: vendor/autoload.php
